### ISSUE TITLE
Example notebook: Warnings when running `import qsharp` for the first time

### ISSUE THREAD

**Issue by ltalirz** [microsoft/qdk-python#185]
![image](https://user-images.githubusercontent.com/1053245/142651171-72b94bf5-758a-4e41-8d9c-6f7b60d5e600.png)

The following cells of the notebook (including the actual simulations) work fine, so it seems like these warnings can be ignored.
Perhaps there is a way to avoid/silence these warnings?

Running in a conda environment under Ubuntu 20.04 (WSL)

**Comment by ltalirz** [comment]
https://github.com/microsoft/qdk-python/pull/187 gives me a later azure.quantum version (0.20 instead of 0.18) but the errors upon import remain

**Comment by cgranade** [comment]
These errors are Q# errors due to the `Microsoft.Quantum.Chemistry` Q# package not having been loaded yet. The package is loaded later by importing `qdk.chemistry.broombridge`, which imports `qsharp.chemistry`, and in turn calls out to `qsharp.packages.add("Microsoft.Quantum.Chemistry")`. The later `qsharp.reload()` call that rebuilds Q# sources then succeeds since all needed packages are present at that point.

Typically this is solved by adding a Q# project file that tells the IQ# kernel (used by Q# + Python interop workflows) what Q# packages are needed at initial import time. See https://docs.microsoft.com/azure/quantum/user-guide/host-programs?tabs=tabid-python#using-q-code-from-other-projects-or-packages for more details.

**Comment by ltalirz** [comment]
Thanks for the explanation! That should be enough for me to fix it
